/*
 * Generated by JasperReports - 28/01/16 04:15 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class cantidadTramitesTotales_1454015720612_543641 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_ANO = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_USUARIO = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillField field_ABRIL = null;
    private JRFillField field_TOT_DIC = null;
    private JRFillField field_TOT_ENERO = null;
    private JRFillField field_TOTAL = null;
    private JRFillField field_FEBRERO = null;
    private JRFillField field_DICIEMBRE = null;
    private JRFillField field_TOT_MARZO = null;
    private JRFillField field_TRAMITE = null;
    private JRFillField field_TOT_JULIO = null;
    private JRFillField field_TOT_SEPT = null;
    private JRFillField field_AGOSTO = null;
    private JRFillField field_TOT_AGOSTO = null;
    private JRFillField field_ENERO = null;
    private JRFillField field_TOT_NOV = null;
    private JRFillField field_TOT_ABRIL = null;
    private JRFillField field_OCTUBRE = null;
    private JRFillField field_TOT_MAYO = null;
    private JRFillField field_MARZO = null;
    private JRFillField field_JULIO = null;
    private JRFillField field_TOT_FEBRERO = null;
    private JRFillField field_NOVIEMBRE = null;
    private JRFillField field_JUNIO = null;
    private JRFillField field_TOT_JUNIO = null;
    private JRFillField field_MAYO = null;
    private JRFillField field_TOTAL2 = null;
    private JRFillField field_SEPTIEMBRE = null;
    private JRFillField field_TOT_OCTUBRE = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_T_ENERO = null;
    private JRFillVariable variable_T_FEBRERO = null;
    private JRFillVariable variable_T_MARZO = null;
    private JRFillVariable variable_T_ABRIL = null;
    private JRFillVariable variable_T_MAYO = null;
    private JRFillVariable variable_T_JUNIO = null;
    private JRFillVariable variable_T_JULIO = null;
    private JRFillVariable variable_T_AGOSTO = null;
    private JRFillVariable variable_T_SEPT = null;
    private JRFillVariable variable_T_OCTUBRE = null;
    private JRFillVariable variable_T_NOVIEMBRE = null;
    private JRFillVariable variable_T_DICIEMBRE = null;
    private JRFillVariable variable_T_TOTAL = null;
    private JRFillVariable variable_TT_ENERO = null;
    private JRFillVariable variable_TT_FEBRERO = null;
    private JRFillVariable variable_TT_MARZO = null;
    private JRFillVariable variable_TT_ABRIL = null;
    private JRFillVariable variable_TT_MAYO = null;
    private JRFillVariable variable_TT_JUNIO = null;
    private JRFillVariable variable_TT_JULIO = null;
    private JRFillVariable variable_TT_AGOSTO = null;
    private JRFillVariable variable_TT_SEPT = null;
    private JRFillVariable variable_TT_OCTUBRE = null;
    private JRFillVariable variable_TT_NOV = null;
    private JRFillVariable variable_TT_DIC = null;
    private JRFillVariable variable_TT_TOTAL = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_ANO = (JRFillParameter)pm.get("ANO");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_USUARIO = (JRFillParameter)pm.get("USUARIO");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_ABRIL = (JRFillField)fm.get("ABRIL");
        field_TOT_DIC = (JRFillField)fm.get("TOT_DIC");
        field_TOT_ENERO = (JRFillField)fm.get("TOT_ENERO");
        field_TOTAL = (JRFillField)fm.get("TOTAL");
        field_FEBRERO = (JRFillField)fm.get("FEBRERO");
        field_DICIEMBRE = (JRFillField)fm.get("DICIEMBRE");
        field_TOT_MARZO = (JRFillField)fm.get("TOT_MARZO");
        field_TRAMITE = (JRFillField)fm.get("TRAMITE");
        field_TOT_JULIO = (JRFillField)fm.get("TOT_JULIO");
        field_TOT_SEPT = (JRFillField)fm.get("TOT_SEPT");
        field_AGOSTO = (JRFillField)fm.get("AGOSTO");
        field_TOT_AGOSTO = (JRFillField)fm.get("TOT_AGOSTO");
        field_ENERO = (JRFillField)fm.get("ENERO");
        field_TOT_NOV = (JRFillField)fm.get("TOT_NOV");
        field_TOT_ABRIL = (JRFillField)fm.get("TOT_ABRIL");
        field_OCTUBRE = (JRFillField)fm.get("OCTUBRE");
        field_TOT_MAYO = (JRFillField)fm.get("TOT_MAYO");
        field_MARZO = (JRFillField)fm.get("MARZO");
        field_JULIO = (JRFillField)fm.get("JULIO");
        field_TOT_FEBRERO = (JRFillField)fm.get("TOT_FEBRERO");
        field_NOVIEMBRE = (JRFillField)fm.get("NOVIEMBRE");
        field_JUNIO = (JRFillField)fm.get("JUNIO");
        field_TOT_JUNIO = (JRFillField)fm.get("TOT_JUNIO");
        field_MAYO = (JRFillField)fm.get("MAYO");
        field_TOTAL2 = (JRFillField)fm.get("TOTAL2");
        field_SEPTIEMBRE = (JRFillField)fm.get("SEPTIEMBRE");
        field_TOT_OCTUBRE = (JRFillField)fm.get("TOT_OCTUBRE");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_T_ENERO = (JRFillVariable)vm.get("T_ENERO");
        variable_T_FEBRERO = (JRFillVariable)vm.get("T_FEBRERO");
        variable_T_MARZO = (JRFillVariable)vm.get("T_MARZO");
        variable_T_ABRIL = (JRFillVariable)vm.get("T_ABRIL");
        variable_T_MAYO = (JRFillVariable)vm.get("T_MAYO");
        variable_T_JUNIO = (JRFillVariable)vm.get("T_JUNIO");
        variable_T_JULIO = (JRFillVariable)vm.get("T_JULIO");
        variable_T_AGOSTO = (JRFillVariable)vm.get("T_AGOSTO");
        variable_T_SEPT = (JRFillVariable)vm.get("T_SEPT");
        variable_T_OCTUBRE = (JRFillVariable)vm.get("T_OCTUBRE");
        variable_T_NOVIEMBRE = (JRFillVariable)vm.get("T_NOVIEMBRE");
        variable_T_DICIEMBRE = (JRFillVariable)vm.get("T_DICIEMBRE");
        variable_T_TOTAL = (JRFillVariable)vm.get("T_TOTAL");
        variable_TT_ENERO = (JRFillVariable)vm.get("TT_ENERO");
        variable_TT_FEBRERO = (JRFillVariable)vm.get("TT_FEBRERO");
        variable_TT_MARZO = (JRFillVariable)vm.get("TT_MARZO");
        variable_TT_ABRIL = (JRFillVariable)vm.get("TT_ABRIL");
        variable_TT_MAYO = (JRFillVariable)vm.get("TT_MAYO");
        variable_TT_JUNIO = (JRFillVariable)vm.get("TT_JUNIO");
        variable_TT_JULIO = (JRFillVariable)vm.get("TT_JULIO");
        variable_TT_AGOSTO = (JRFillVariable)vm.get("TT_AGOSTO");
        variable_TT_SEPT = (JRFillVariable)vm.get("TT_SEPT");
        variable_TT_OCTUBRE = (JRFillVariable)vm.get("TT_OCTUBRE");
        variable_TT_NOV = (JRFillVariable)vm.get("TT_NOV");
        variable_TT_DIC = (JRFillVariable)vm.get("TT_DIC");
        variable_TT_TOTAL = (JRFillVariable)vm.get("TT_TOTAL");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_ENERO.getValue()));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_FEBRERO.getValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MARZO.getValue()));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_ABRIL.getValue()));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MAYO.getValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_JUNIO.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_JULIO.getValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AGOSTO.getValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_SEPTIEMBRE.getValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_OCTUBRE.getValue()));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_NOVIEMBRE.getValue()));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DICIEMBRE.getValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL2.getValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_ENERO.getValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_FEBRERO.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_MARZO.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_ABRIL.getValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_MAYO.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_JULIO.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_JULIO.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_AGOSTO.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_SEPT.getValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_OCTUBRE.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_NOV.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_DIC.getValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL.getValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.String)("C:\\Civitrans\\transito\\web\\paginas\\reports\\images\\logo_.png");//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.util.Date)(new java.util.Date());//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_USUARIO.getValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ANO.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.String)(((java.lang.String)field_TRAMITE.getValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_ENERO.getValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_FEBRERO.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MARZO.getValue()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_ABRIL.getValue()));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MAYO.getValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_JUNIO.getValue()));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_JULIO.getValue()));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AGOSTO.getValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_SEPTIEMBRE.getValue()));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_OCTUBRE.getValue()));//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DICIEMBRE.getValue()));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL.getValue()));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_NOVIEMBRE.getValue()));//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_ENERO.getValue()));//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_FEBRERO.getValue()));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_MARZO.getValue()));//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_ABRIL.getValue()));//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_MAYO.getValue()));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_JUNIO.getValue()));//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_JULIO.getValue()));//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_AGOSTO.getValue()));//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_SEPT.getValue()));//$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_OCTUBRE.getValue()));//$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_NOV.getValue()));//$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_DIC.getValue()));//$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL2.getValue()));//$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_ENERO.getValue()));//$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_FEBRERO.getValue()));//$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_MARZO.getValue()));//$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_ABRIL.getValue()));//$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_MAYO.getValue()));//$JR_EXPR_ID=69$
                break;
            }
            case 70 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_JUNIO.getValue()));//$JR_EXPR_ID=70$
                break;
            }
            case 71 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_JULIO.getValue()));//$JR_EXPR_ID=71$
                break;
            }
            case 72 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_AGOSTO.getValue()));//$JR_EXPR_ID=72$
                break;
            }
            case 73 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_SEPT.getValue()));//$JR_EXPR_ID=73$
                break;
            }
            case 74 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_OCTUBRE.getValue()));//$JR_EXPR_ID=74$
                break;
            }
            case 75 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_NOVIEMBRE.getValue()));//$JR_EXPR_ID=75$
                break;
            }
            case 76 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_DICIEMBRE.getValue()));//$JR_EXPR_ID=76$
                break;
            }
            case 77 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_TOTAL.getValue()));//$JR_EXPR_ID=77$
                break;
            }
            case 78 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_ENERO.getValue()));//$JR_EXPR_ID=78$
                break;
            }
            case 79 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_FEBRERO.getValue()));//$JR_EXPR_ID=79$
                break;
            }
            case 80 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_MARZO.getValue()));//$JR_EXPR_ID=80$
                break;
            }
            case 81 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_ABRIL.getValue()));//$JR_EXPR_ID=81$
                break;
            }
            case 82 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_MAYO.getValue()));//$JR_EXPR_ID=82$
                break;
            }
            case 83 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_JUNIO.getValue()));//$JR_EXPR_ID=83$
                break;
            }
            case 84 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_JULIO.getValue()));//$JR_EXPR_ID=84$
                break;
            }
            case 85 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_AGOSTO.getValue()));//$JR_EXPR_ID=85$
                break;
            }
            case 86 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_SEPT.getValue()));//$JR_EXPR_ID=86$
                break;
            }
            case 87 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_OCTUBRE.getValue()));//$JR_EXPR_ID=87$
                break;
            }
            case 88 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_NOV.getValue()));//$JR_EXPR_ID=88$
                break;
            }
            case 89 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_DIC.getValue()));//$JR_EXPR_ID=89$
                break;
            }
            case 90 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_TOTAL.getValue()));//$JR_EXPR_ID=90$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_ENERO.getOldValue()));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_FEBRERO.getOldValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MARZO.getOldValue()));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_ABRIL.getOldValue()));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MAYO.getOldValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_JUNIO.getOldValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_JULIO.getOldValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AGOSTO.getOldValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_SEPTIEMBRE.getOldValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_OCTUBRE.getOldValue()));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_NOVIEMBRE.getOldValue()));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DICIEMBRE.getOldValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL2.getOldValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_ENERO.getOldValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_FEBRERO.getOldValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_MARZO.getOldValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_ABRIL.getOldValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_MAYO.getOldValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_JULIO.getOldValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_JULIO.getOldValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_AGOSTO.getOldValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_SEPT.getOldValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_OCTUBRE.getOldValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_NOV.getOldValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_DIC.getOldValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL.getOldValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.String)("C:\\Civitrans\\transito\\web\\paginas\\reports\\images\\logo_.png");//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.util.Date)(new java.util.Date());//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_USUARIO.getValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ANO.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.String)(((java.lang.String)field_TRAMITE.getOldValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_ENERO.getOldValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_FEBRERO.getOldValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MARZO.getOldValue()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_ABRIL.getOldValue()));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MAYO.getOldValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_JUNIO.getOldValue()));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_JULIO.getOldValue()));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AGOSTO.getOldValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_SEPTIEMBRE.getOldValue()));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_OCTUBRE.getOldValue()));//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DICIEMBRE.getOldValue()));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL.getOldValue()));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_NOVIEMBRE.getOldValue()));//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_ENERO.getOldValue()));//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_FEBRERO.getOldValue()));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_MARZO.getOldValue()));//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_ABRIL.getOldValue()));//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_MAYO.getOldValue()));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_JUNIO.getOldValue()));//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_JULIO.getOldValue()));//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_AGOSTO.getOldValue()));//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_SEPT.getOldValue()));//$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_OCTUBRE.getOldValue()));//$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_NOV.getOldValue()));//$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_DIC.getOldValue()));//$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL2.getOldValue()));//$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_ENERO.getOldValue()));//$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_FEBRERO.getOldValue()));//$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_MARZO.getOldValue()));//$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_ABRIL.getOldValue()));//$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_MAYO.getOldValue()));//$JR_EXPR_ID=69$
                break;
            }
            case 70 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_JUNIO.getOldValue()));//$JR_EXPR_ID=70$
                break;
            }
            case 71 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_JULIO.getOldValue()));//$JR_EXPR_ID=71$
                break;
            }
            case 72 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_AGOSTO.getOldValue()));//$JR_EXPR_ID=72$
                break;
            }
            case 73 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_SEPT.getOldValue()));//$JR_EXPR_ID=73$
                break;
            }
            case 74 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_OCTUBRE.getOldValue()));//$JR_EXPR_ID=74$
                break;
            }
            case 75 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_NOVIEMBRE.getOldValue()));//$JR_EXPR_ID=75$
                break;
            }
            case 76 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_DICIEMBRE.getOldValue()));//$JR_EXPR_ID=76$
                break;
            }
            case 77 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_TOTAL.getOldValue()));//$JR_EXPR_ID=77$
                break;
            }
            case 78 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_ENERO.getOldValue()));//$JR_EXPR_ID=78$
                break;
            }
            case 79 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_FEBRERO.getOldValue()));//$JR_EXPR_ID=79$
                break;
            }
            case 80 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_MARZO.getOldValue()));//$JR_EXPR_ID=80$
                break;
            }
            case 81 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_ABRIL.getOldValue()));//$JR_EXPR_ID=81$
                break;
            }
            case 82 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_MAYO.getOldValue()));//$JR_EXPR_ID=82$
                break;
            }
            case 83 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_JUNIO.getOldValue()));//$JR_EXPR_ID=83$
                break;
            }
            case 84 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_JULIO.getOldValue()));//$JR_EXPR_ID=84$
                break;
            }
            case 85 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_AGOSTO.getOldValue()));//$JR_EXPR_ID=85$
                break;
            }
            case 86 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_SEPT.getOldValue()));//$JR_EXPR_ID=86$
                break;
            }
            case 87 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_OCTUBRE.getOldValue()));//$JR_EXPR_ID=87$
                break;
            }
            case 88 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_NOV.getOldValue()));//$JR_EXPR_ID=88$
                break;
            }
            case 89 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_DIC.getOldValue()));//$JR_EXPR_ID=89$
                break;
            }
            case 90 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_TOTAL.getOldValue()));//$JR_EXPR_ID=90$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_ENERO.getValue()));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_FEBRERO.getValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MARZO.getValue()));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_ABRIL.getValue()));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MAYO.getValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_JUNIO.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_JULIO.getValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AGOSTO.getValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_SEPTIEMBRE.getValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_OCTUBRE.getValue()));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_NOVIEMBRE.getValue()));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DICIEMBRE.getValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL2.getValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_ENERO.getValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_FEBRERO.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_MARZO.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_ABRIL.getValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_MAYO.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_JULIO.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_JULIO.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_AGOSTO.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_SEPT.getValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_OCTUBRE.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_NOV.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_DIC.getValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL.getValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.String)("C:\\Civitrans\\transito\\web\\paginas\\reports\\images\\logo_.png");//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.util.Date)(new java.util.Date());//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_USUARIO.getValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ANO.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.String)(((java.lang.String)field_TRAMITE.getValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_ENERO.getValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_FEBRERO.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MARZO.getValue()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_ABRIL.getValue()));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MAYO.getValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_JUNIO.getValue()));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_JULIO.getValue()));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AGOSTO.getValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_SEPTIEMBRE.getValue()));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_OCTUBRE.getValue()));//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DICIEMBRE.getValue()));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL.getValue()));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_NOVIEMBRE.getValue()));//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_ENERO.getValue()));//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_FEBRERO.getValue()));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_MARZO.getValue()));//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_ABRIL.getValue()));//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_MAYO.getValue()));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_JUNIO.getValue()));//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_JULIO.getValue()));//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_AGOSTO.getValue()));//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_SEPT.getValue()));//$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_OCTUBRE.getValue()));//$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_NOV.getValue()));//$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_DIC.getValue()));//$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL2.getValue()));//$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_ENERO.getEstimatedValue()));//$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_FEBRERO.getEstimatedValue()));//$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_MARZO.getEstimatedValue()));//$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_ABRIL.getEstimatedValue()));//$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_MAYO.getEstimatedValue()));//$JR_EXPR_ID=69$
                break;
            }
            case 70 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_JUNIO.getEstimatedValue()));//$JR_EXPR_ID=70$
                break;
            }
            case 71 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_JULIO.getEstimatedValue()));//$JR_EXPR_ID=71$
                break;
            }
            case 72 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_AGOSTO.getEstimatedValue()));//$JR_EXPR_ID=72$
                break;
            }
            case 73 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_SEPT.getEstimatedValue()));//$JR_EXPR_ID=73$
                break;
            }
            case 74 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_OCTUBRE.getEstimatedValue()));//$JR_EXPR_ID=74$
                break;
            }
            case 75 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_NOVIEMBRE.getEstimatedValue()));//$JR_EXPR_ID=75$
                break;
            }
            case 76 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_DICIEMBRE.getEstimatedValue()));//$JR_EXPR_ID=76$
                break;
            }
            case 77 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_T_TOTAL.getEstimatedValue()));//$JR_EXPR_ID=77$
                break;
            }
            case 78 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_ENERO.getEstimatedValue()));//$JR_EXPR_ID=78$
                break;
            }
            case 79 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_FEBRERO.getEstimatedValue()));//$JR_EXPR_ID=79$
                break;
            }
            case 80 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_MARZO.getEstimatedValue()));//$JR_EXPR_ID=80$
                break;
            }
            case 81 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_ABRIL.getEstimatedValue()));//$JR_EXPR_ID=81$
                break;
            }
            case 82 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_MAYO.getEstimatedValue()));//$JR_EXPR_ID=82$
                break;
            }
            case 83 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_JUNIO.getEstimatedValue()));//$JR_EXPR_ID=83$
                break;
            }
            case 84 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_JULIO.getEstimatedValue()));//$JR_EXPR_ID=84$
                break;
            }
            case 85 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_AGOSTO.getEstimatedValue()));//$JR_EXPR_ID=85$
                break;
            }
            case 86 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_SEPT.getEstimatedValue()));//$JR_EXPR_ID=86$
                break;
            }
            case 87 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_OCTUBRE.getEstimatedValue()));//$JR_EXPR_ID=87$
                break;
            }
            case 88 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_NOV.getEstimatedValue()));//$JR_EXPR_ID=88$
                break;
            }
            case 89 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_DIC.getEstimatedValue()));//$JR_EXPR_ID=89$
                break;
            }
            case 90 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TT_TOTAL.getEstimatedValue()));//$JR_EXPR_ID=90$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
